name: Build and test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GET_GAUCHE_URL: https://raw.githubusercontent.com/shirok/get-gauche/master
    steps:
    - uses: actions/checkout@v3
    - uses: shirok/setup-gauche@v1
    - name: Install dependencies
      run: |
        sudo apt install -y libmecab-dev mecab-ipadic-utf8
    - name: Build and check
      run: |
        ./configure
        make
        make -s check
        make -s check-dep
